version: '3.8'

services:
  backend:
    build: .
    container_name: multiview-backend
    ports:
      - "9292:9292"
    environment:
      - PORT=9292
      - ENCODER_PREFERENCE=auto  # Options: auto, nvidia, intel, amd, cpu
      - M3U_SOURCE=http://host.docker.internal:9191/output/m3u?direct=true
      - IDLE_TIMEOUT=60
      - DEFAULT_UA=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
      - HLS_TIME=2
      - HLS_LIST_SIZE=10
    volumes:
      - ./out:/out
    # Intel/AMD hardware encoding support
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    # NVIDIA GPU support (works alongside Intel/AMD - auto-detection picks best)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, video]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: multiview-frontend
    ports:
      - "9393:9393"
    environment:
      # API URL is now dynamic (uses window.location.hostname on client side)
      # No need to hardcode IP - works with localhost and LAN IP automatically
      - PORT=9393
      - HOSTNAME=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped
